import { Scale, FileText, AlertCircle, Shield } from "lucide-react";

export default function Terms() {
  return (
    <div className="bg-slate-50 min-h-screen py-20 px-6">
      <div className="max-w-3xl mx-auto bg-white p-10 md:p-16 rounded-[32px] shadow-sm border border-slate-200">
        <div className="flex items-center gap-4 mb-8">
          <div className="bg-blue-100 p-3 rounded-2xl">
            <Scale className="text-blue-700" size={32} />
          </div>
          <h1 className="text-4xl font-black text-slate-900 tracking-tight">Terms of Service</h1>
        </div>

        <div className="space-y-8 text-slate-600 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">1. Use of Service</h2>
            <p>
              QuickReport UK provides an AI-driven tool to assist in the generation of site reports. By using this service, you agree to provide accurate information and use the tool solely for professional reporting purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3 text-red-600 flex items-center gap-2">
              <AlertCircle size={20} /> 2. Accuracy of AI Content
            </h2>
            <p className="font-medium bg-red-50 p-4 rounded-xl border border-red-100">
              The reports generated by our AI are based on your input. While we strive for accuracy, AI can occasionally hallucinate or misinterpret data. <strong>Users are legally responsible for reviewing and verifying all reports before final submission or sign-off.</strong>
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">3. Subscription & Credits</h2>
            <p>
              Free accounts are limited to 2 reports per day. Credits do not roll over. Pro and Business accounts are subject to the specific limits defined at the time of purchase.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">4. Limitation of Liability</h2>
            <p>
              QuickReport UK shall not be held liable for any accidents, legal disputes, or HSE fines resulting from the use of reports generated by this tool. Final safety oversight remains the duty of the site manager.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-100 text-center">
          <p className="text-slate-400 text-sm">Last Updated: December 2024</p>
        </div>
      </div>
    </div>
  );
}